export const usersdata = [
  {
    name: "Aarav Mehta",
    gender: "Male",
    city: "Mumbai",
    email: "aarav.mehta@example.com",
    phone: "+91-9876543210",
  },
  {
    name: "Isha Sharma",
    gender: "Female",
    city: "Delhi",
    email: "isha.sharma@example.com",
    phone: "+91-9811122233",
  },
  {
    name: "Rohan Gupta",
    gender: "Male",
    city: "Bengaluru",
    email: "rohan.gupta@example.com",
    phone: "+91-9123456789",
  },
  {
    name: "Ananya Verma",
    gender: "Female",
    city: "Chennai",
    email: "ananya.verma@example.com",
    phone: "+91-9765432109",
  },
  {
    name: "Dev Patel",
    gender: "Male",
    city: "Ahmedabad",
    email: "dev.patel@example.com",
    phone: "+91-9833322110",
  },
  {
    name: "Priya Reddy",
    gender: "Female",
    city: "Hyderabad",
    email: "priya.reddy@example.com",
    phone: "+91-9898989898",
  },
  {
    name: "Kabir Singh",
    gender: "Male",
    city: "Pune",
    email: "kabir.singh@example.com",
    phone: "+91-9000011111",
  },
  {
    name: "Simran Kaur",
    gender: "Female",
    city: "Amritsar",
    email: "simran.kaur@example.com",
    phone: "+91-9876554321",
  },
  {
    name: "Arjun Das",
    gender: "Male",
    city: "Kolkata",
    email: "arjun.das@example.com",
    phone: "+91-9090909090",
  },
  {
    name: "Neha Nair",
    gender: "Female",
    city: "Kochi",
    email: "neha.nair@example.com",
    phone: "+91-9777722233",
  },
  {
    name: "Yash Raj",
    gender: "Male",
    city: "Bhopal",
    email: "yash.raj@example.com",
    phone: "+91-9111111234",
  },
  {
    name: "Sanya Iyer",
    gender: "Female",
    city: "Mysuru",
    email: "sanya.iyer@example.com",
    phone: "+91-9345612390",
  },
  {
    name: "Karan Thakur",
    gender: "Male",
    city: "Shimla",
    email: "karan.thakur@example.com",
    phone: "+91-9834567812",
  },
  {
    name: "Pooja Deshmukh",
    gender: "Female",
    city: "Nagpur",
    email: "pooja.deshmukh@example.com",
    phone: "+91-9933445566",
  },
  {
    name: "Rajeev Sinha",
    gender: "Male",
    city: "Patna",
    email: "rajeev.sinha@example.com",
    phone: "+91-9004433221",
  },
  {
    name: "Meera Joseph",
    gender: "Female",
    city: "Thiruvananthapuram",
    email: "meera.joseph@example.com",
    phone: "+91-9888877766",
  },
  {
    name: "Abhay Mishra",
    gender: "Male",
    city: "Lucknow",
    email: "abhay.mishra@example.com",
    phone: "+91-9098765432",
  },
  {
    name: "Tanya Aggarwal",
    gender: "Female",
    city: "Gurgaon",
    email: "tanya.aggarwal@example.com",
    phone: "+91-9877001100",
  },
  {
    name: "Nikhil Kumar",
    gender: "Male",
    city: "Noida",
    email: "nikhil.kumar@example.com",
    phone: "+91-9023456712",
  },
  {
    name: "Ritika Bhatt",
    gender: "Female",
    city: "Dehradun",
    email: "ritika.bhatt@example.com",
    phone: "+91-9333445566",
  },
  {
    name: "Vikram Chauhan",
    gender: "Male",
    city: "Jaipur",
    email: "vikram.chauhan@example.com",
    phone: "+91-9888999000",
  },
  {
    name: "Sneha Pandey",
    gender: "Female",
    city: "Varanasi",
    email: "sneha.pandey@example.com",
    phone: "+91-9777755555",
  },
  {
    name: "Ravi Joshi",
    gender: "Male",
    city: "Indore",
    email: "ravi.joshi@example.com",
    phone: "+91-9444444444",
  },
  {
    name: "Alisha Khan",
    gender: "Female",
    city: "Srinagar",
    email: "alisha.khan@example.com",
    phone: "+91-9555555555",
  },
  {
    name: "Sameer Bhat",
    gender: "Male",
    city: "Jammu",
    email: "sameer.bhat@example.com",
    phone: "+91-9666666666",
  },
  {
    name: "Pallavi Ghosh",
    gender: "Female",
    city: "Howrah",
    email: "pallavi.ghosh@example.com",
    phone: "+91-9777665544",
  },
  {
    name: "Ramesh Iyer",
    gender: "Male",
    city: "Madurai",
    email: "ramesh.iyer@example.com",
    phone: "+91-9123451234",
  },
  {
    name: "Kavya Kapoor",
    gender: "Female",
    city: "Ludhiana",
    email: "kavya.kapoor@example.com",
    phone: "+91-9999999999",
  },
  {
    name: "Ajay Naik",
    gender: "Male",
    city: "Panaji",
    email: "ajay.naik@example.com",
    phone: "+91-9222222222",
  },
  {
    name: "Diya Pillai",
    gender: "Female",
    city: "Thrissur",
    email: "diya.pillai@example.com",
    phone: "+91-9333998877",
  },
];
